### ISSUE TITLE
Codeboy 

### ISSUE THREAD

**Issue by Batchno1212** [bimalkaf/Android_LoginUI#1]
![IMG_20220915_143916](https://user-images.githubusercontent.com/112309132/190363213-487b87aa-e1fc-443b-8b96-1e01ea20dba9.jpg)
Help me?``

**Comment by devbrath-bhatt-pujari** [comment]
It should be @+id/loginbtn
![image](https://user-images.githubusercontent.com/96042614/196054932-450d1242-779b-4235-a323-0902a288bec8.png)
